### ISSUE TITLE
Feature Request: Add configuration for xy-offset of home postion / Control Servos with disconnected printer

### ISSUE THREAD

**Issue by der-den** [mledan/OctoPrint-EasyServo#16]
Hi,

my camera shows in the "HOME" direction not on the bed. So i would very nice i can setup a offset for the home position.

And, if possible, i like to use the camera for surveillance the full of my room (buzzwords: "child and cats"). But to control the servos i must turn on the printer. Can you change this?

Thanks.

**Comment by franfrandev** [comment]
Hi!

There is already a "xAutoAngle" and the same for the y axis in the plugin settings. This is set to 90° by default, but you can change it for sure.
I'll make the buttons usable even if the printer is turned off in the next update

**Comment by der-den** [comment]
xAutoAngle: Ohh, who can read has a clear advantage
printer is turned off: perfect, thanks!
