### ISSUE TITLE
Pi Zero compatible?

### ISSUE THREAD

**Issue by WWE-Corey** [mledan/OctoPrint-EasyServo#19]
Assuming I identify the same GPIO (PWM0 & PWM1), will this work on on a Piz Zero?

**Comment by franfrandev** [comment]
Looking at the pigpio library http://abyz.me.uk/rpi/pigpio/ I don't see why it would not work with a Pi Zero. Though, pins 0 and 1 may not work without any additional hardware. Also, please note that using a Pi Zero is not recommended for Octoprint https://github.com/guysoft/OctoPi/issues/318

**Comment by WWE-Corey** [comment]
Thank you. I may have misunderstood after many hours of searching. I was wanting to operate and control this pi zero separately - I run Octoprint on a Pi 4 but did not want to run ribbon and servo wires into the enclosure.
