### ISSUE TITLE
Update wiring diagram to show common ground between external PS and Pi

### ISSUE THREAD

**Issue by mcstoufer** [mledan/OctoPrint-EasyServo#8]
I was having a lot of noise on the two pins before I tied a pi ground pin to the same breadboard row that the ground from the external PS was tied to. Once done, no more noise and servos only moved on command.

Requesting that the diagram be updated, or amended to inform the user that a common ground is recommended.

**Comment by franfrandev** [comment]
Thanks for this, Yep grounding is very important in electronics, I'm updating now!

**Comment by franfrandev** [comment]
In my case, I could wire the servos on the pi directly. Maybe you could try this (if your power supply is available)

**Comment by franfrandev** [comment]
Please see the update below the diagram

**Comment by mcstoufer** [comment]
> In my case, I could wire the servos on the pi directly. Maybe you could try this (if your power supply is available)

I tried that first, but OctoPrint complained it was seeing a lot of undervolt warnings when driving those two servos.
